-- 세대별 타공 수를 계산하기 위한 현장 타입표·옵션표.
--
-- 설계:
-- - 세대 타공 수 = 라인 타입의 기본 타공 수 + 그 세대에 붙은 옵션들의 가감(±) 합.
-- - 타입은 현장마다 타공 수가 다르므로 현장(site)에 달린다. 라인은 지금처럼 building_lines.unit_type에
--   타입 이름을 글자로 들고 있고, 같은 현장의 타입표에서 이름으로 찾아 쓴다. 기존 세대표 데이터와
--   이전 버전 앱을 그대로 둘 수 있고, 타입 이름을 바꿀 때는 앱이 라인 값도 함께 바꿔준다.
-- - 같은 타입이라도 옵션(확장·알파룸 등)에 따라 타공 수가 달라지는 세대가 있다. 옵션도 현장에 달리고,
--   세대↔옵션 연결은 unit_options에 (building_id, line_no, floor)로 저장한다. 옵션 하나가 수십 세대에
--   붙는 경우가 많아서, 옵션 타공 수가 바뀌어도 옵션표 한 곳만 고치면 된다.
-- - 세대표를 공유하는 현장은 동이 원본 현장에 달려 있으므로 타입·옵션도 원본 현장 기준으로 붙는다.
-- - 세대표·공구와 같이 로그인한 팀원이면 누구나 관리할 수 있다. 타공 현황 화면만 팀장 이상이다.
create table if not exists public.site_unit_types (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.sites (id) on delete cascade,
  name text not null,
  -- null이면 아직 타공 수를 정하지 않은 타입이다(타공 현황에서 미설정으로 따로 센다)
  hole_count integer check (hole_count >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (site_id, name)
);

create table if not exists public.site_unit_options (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.sites (id) on delete cascade,
  name text not null,
  hole_delta integer not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (site_id, name)
);

-- 옵션을 지우면 붙어 있던 세대 연결도 같이 지워지고, 동을 지우면 그 동의 연결도 같이 지워진다.
create table if not exists public.unit_options (
  building_id bigint not null references public.buildings (id) on delete cascade,
  line_no integer not null,
  floor integer not null,
  option_id bigint not null references public.site_unit_options (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (building_id, line_no, floor, option_id)
);

create index if not exists idx_unit_options_option on public.unit_options (option_id);

-- 멀티팀: 다른 팀 데이터가 보이지 않도록 team_id와 팀 격리 정책을 다른 테이블과 같은 방식으로 건다.
-- (20260916040000_multi_team.sql 참고. RESTRICTIVE라 아래 관리 정책과 AND로 묶인다)
do $$
declare
  tbl text;
begin
  foreach tbl in array array['site_unit_types', 'site_unit_options', 'unit_options'] loop
    execute format('alter table public.%I add column if not exists team_id bigint not null default public.current_team_id() references public.teams (id)', tbl);
    execute format('create index if not exists %I on public.%I (team_id)', 'idx_' || tbl || '_team', tbl);
    execute format('alter table public.%I enable row level security', tbl);

    execute format('drop policy if exists "세대 타공 관리" on public.%I', tbl);
    execute format('create policy "세대 타공 관리" on public.%I using (auth.uid() is not null)', tbl);

    execute format('drop policy if exists "팀 격리" on public.%I', tbl);
    execute format(
      'create policy "팀 격리" on public.%I as restrictive for all '
      'using (team_id = (select public.current_team_id())) '
      'with check (team_id = (select public.current_team_id()))',
      tbl
    );

    execute format('grant select, insert, update, delete on public.%I to authenticated', tbl);
  end loop;
end
$$;

grant select, usage on sequence public.site_unit_types_id_seq to authenticated;
grant select, usage on sequence public.site_unit_options_id_seq to authenticated;

-- 기존 세대표에 이미 적혀 있는 타입 이름을 현장 타입표로 옮겨 둔다. 타공 수는 아직 모르므로 비워 두고,
-- 타공 현황 화면이 이런 타입의 세대를 미설정으로 따로 알려준다.
insert into public.site_unit_types (site_id, name, hole_count, team_id)
select distinct b.site_id, trim(l.unit_type), null::integer, b.team_id
from public.building_lines l
join public.buildings b on b.id = l.building_id
where l.unit_type is not null and trim(l.unit_type) <> ''
on conflict (site_id, name) do nothing;
