-- 메인 세대표를 공구(工區) 단위로 나눠 볼 수 있게 한다. (예: 1공구 101·102·104동, 2공구 103·105동)
--
-- 설계:
-- - 한 동은 한 공구에만 속한다. 그래서 중간 테이블 없이 buildings.section_id 하나로 둔다.
-- - 공구를 지우면 그 동들은 다시 "미지정"이 된다(on delete set null). 동과 세대표 기록은 그대로 남는다.
-- - 공구는 동과 마찬가지로 현장에 달린다. 세대표를 공유하는 현장은 동이 원본 현장에 달려 있으므로
--   공구도 원본 현장 기준으로 붙어 공유받는 현장에서 똑같이 보인다.
create table if not exists public.site_sections (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.sites (id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_site_sections_site on public.site_sections (site_id, sort_order);

alter table public.buildings
  add column if not exists section_id bigint references public.site_sections (id) on delete set null;

create index if not exists idx_buildings_section on public.buildings (section_id);

alter table public.site_sections enable row level security;

-- 세대표·동과 동일하게, 로그인한 팀원이면 누구나 공구를 만들고 고칠 수 있다.
create policy "공구 관리" on public.site_sections using (auth.uid() is not null);

grant select, insert, update, delete on public.site_sections to authenticated;
grant select, usage on sequence public.site_sections_id_seq to authenticated;

-- 멀티팀: 다른 팀의 공구가 보이지 않도록 team_id와 팀 격리 정책을 다른 테이블과 같은 방식으로 건다.
-- (20260916040000_multi_team.sql 참고. RESTRICTIVE라 기존 정책과 AND로 묶인다)
alter table public.site_sections add column if not exists team_id bigint references public.teams (id);
update public.site_sections set team_id = (select min(id) from public.teams) where team_id is null;
alter table public.site_sections alter column team_id set not null;
alter table public.site_sections alter column team_id set default public.current_team_id();
create index if not exists idx_site_sections_team on public.site_sections (team_id);

drop policy if exists "팀 격리" on public.site_sections;
create policy "팀 격리" on public.site_sections
  as restrictive
  for all
  using (team_id = (select public.current_team_id()))
  with check (team_id = (select public.current_team_id()));
